# Generated by Django 2.1.7 on 2019-03-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='tickets',
        ),
    ]
