# Generated by Django 2.1.7 on 2019-03-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_choice_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='count',
        ),
    ]
