# Generated by Django 2.1.7 on 2019-03-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='有效票'),
        ),
    ]
